In [32]:
import warnings
import pandas as pd

warnings.filterwarnings('ignore', category=pd.errors.PerformanceWarning)

# 1. Read a .csv file from a URL with Pandas

> Target Website: (https://football-data.co.uk/englandm.php)

In [3]:
# reading 1 csv file from the web 
df_premier25 = pd.read_csv('https://football-data.co.uk/mmz4281/2526/E0.csv')

In [4]:
df_premier25.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [6]:
# rename columns 
df_premier25.rename(columns =
                    {
                        'FTHG' : 'Home_Goals',
                        'FTAG' : 'Away_Goals',
                    },
                    inplace = True
                    )

In [7]:
df_premier25.head()

,Div,Date,Time,HomeTeam,AwayTeam,Home_Goals,Away_Goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

# 2. Read a .csv file from multiple URLs with Pandas

- https://football-data.co.uk/mmz4281/2526/E0.csv
- https://football-data.co.uk/mmz4281/2526/E1.csv

**Link: root + season + league**

In [8]:
#link structure 

"https://football-data.co.uk/mmz4281/" + "2526" + "/" + "E0" + ".csv"

'https://football-data.co.uk/mmz4281/2526/E0.csv'

In [9]:
# create a root variable 
root = "https://football-data.co.uk/mmz4281/"

## 2.1 Multiple Leagus

- https://football-data.co.uk/mmz4281/2526/E0.csv
- https://football-data.co.uk/mmz4281/2526/E1.csv
- https://football-data.co.uk/mmz4281/2526/E2.csv
- https://football-data.co.uk/mmz4281/2526/E3.csv
- https://football-data.co.uk/mmz4281/2526/EC.csv

In [10]:
# creating a list of leagus
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']

frames = [] # create an empty list 
 

# looping through leagues, read multiple csv's and append to a list 
for league in leagues: 
    df = pd.read_csv(root + '2526' + '/' + league + '.csv')
    frames.append(df)   #to store each dataframe in the list

In [11]:
# length of frames list
len(frames)

5

In [14]:
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,EC,25/04/2026,12:30,Scunthorpe,Eastleigh,0,1,A,0,1,...,1.85,1.95,NaN,NaN,1.85,1.95,1.80,1.88,NaN,NaN
548,EC,25/04/2026,12:30,Southend,Wealdstone,2,1,H,2,1,...,1.83,1.98,NaN,NaN,1.83,1.98,1.78,1.91,NaN,NaN
549,EC,25/04/2026,12:30,Tamworth,Braintree Town,5,1,H,2,1,...,1.78,2.03,NaN,NaN,1.83,2.03,1.77,1.93,NaN,NaN
550,EC,25/04/2026,12:30,Woking,Halifax,0,1,A,0,0,...,2.08,1.73,NaN,NaN,2.08,1.75,1.99,1.72,NaN,NaN
551,EC,25/04/2026,12:30,Yeovil,Solihull,1,4,A,1,4,...,1.78,2.03,NaN,NaN,1.78,2.03,1.73,1.97,NaN,NaN

## 2.2 Multiple Seasons

In [17]:
for season in range(20, 26):
    print(str(season) + str(season+1)) #to show whats actually happening in the loop

2021
2122
2223
2324
2425
2526

In [35]:
# creating a list of leagus
leagues = ['E0', 'E2', 'E3']

frames = [] # create an empty list 


# loop through range of seasons and insert new column
for league in leagues: 
    for season in range(20, 26):
        try:
            df = pd.read_csv(root + str(season) + str(season+1) + '/' + league + '.csv')
        except Exception:
            print('Failed:', league, season)
            continue
        df.insert(0, 'Season', season) #to insert a new column at the first position
        frames.append(df)

In [ ]:
# 6 season times 3 leagues
len(frames)

18

In [ ]:
frames[0]   # showing the first dataframe in the list

,Season,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,20,E0,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,20,E0,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,20,E0,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04
3,20,E0,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,...,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86
4,20,E0,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,...,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,20,E0,23/05/2021,16:00,Liverpool,Crystal Palace,2,0,H,1,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,20,E0,23/05/2021,16:00,Man City,Everton,5,0,H,2,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,20,E0,23/05/2021,16:00,Sheffield United,Burnley,1,0,H,1,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,20,E0,23/05/2021,16:00,West Ham,Southampton,3,0,H,2,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,20,E0,23/05/2021,16:00,Wolves,Man United,1,2,A,1,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88

In [31]:
frames[6]

,Season,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,20,E2,12/09/2020,15:00,Accrington,Peterboro,2,0,H,1,...,2.03,0.25,2.02,1.83,2.08,1.83,2.09,1.87,2.02,1.81
1,20,E2,12/09/2020,15:00,Crewe,Charlton,0,2,A,0,...,1.88,0.00,1.95,1.90,1.96,1.94,2.00,1.95,1.94,1.89
2,20,E2,12/09/2020,15:00,Doncaster,Milton Keynes Dons,1,1,D,0,...,1.69,-0.25,1.80,2.05,1.81,2.12,1.85,2.12,1.80,2.05
3,20,E2,12/09/2020,15:00,Fleetwood Town,Burton,2,1,H,1,...,1.85,-0.50,1.98,1.88,1.95,1.95,2.06,1.95,1.97,1.86
4,20,E2,12/09/2020,15:00,Gillingham,Hull,0,2,A,0,...,1.86,0.00,1.85,2.00,1.91,2.00,1.93,2.06,1.85,1.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,20,E2,09/05/2021,12:00,Milton Keynes Dons,Rochdale,0,3,A,0,...,2.56,-0.75,1.88,1.98,1.88,2.01,1.96,2.04,1.87,1.97
548,20,E2,09/05/2021,12:00,Oxford,Burton,4,0,H,2,...,2.38,-1.00,1.85,2.00,1.88,2.02,2.11,2.06,1.88,1.95
549,20,E2,09/05/2021,12:00,Portsmouth,Accrington,0,1,A,0,...,2.21,-1.00,1.95,1.90,1.99,1.90,2.07,1.94,1.95,1.88
550,20,E2,09/05/2021,12:00,Sunderland,Northampton,1,1,D,0,...,2.13,-1.25,1.98,1.88,2.02,1.88,2.10,1.91,2.01,1.83
551,20,E2,09/05/2021,12:00,Wigan,Swindon,3,4,A,1,...,2.28,-0.75,1.93,1.93,2.00,1.88,2.01,1.97,1.93,1.90