In [1]:
import pandas as pd

# 1. Read a .csv file from a URL with Pandas

> Target Website: (https://football-data.co.uk/englandm.php)

In [3]:
# reading 1 csv file from the web 
df_premier25 = pd.read_csv('https://football-data.co.uk/mmz4281/2526/E0.csv')

In [4]:
df_premier25.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [6]:
# rename columns 
df_premier25.rename(columns =
                    {
                        'FTHG' : 'Home_Goals',
                        'FTAG' : 'Away_Goals',
                    },
                    inplace = True
                    )

In [7]:
df_premier25.head()

,Div,Date,Time,HomeTeam,AwayTeam,Home_Goals,Away_Goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

# 2. Read a .csv file from multiple URLs with Pandas

- https://football-data.co.uk/mmz4281/2526/E0.csv
- https://football-data.co.uk/mmz4281/2526/E1.csv

**Link: root + season + league**

In [8]:
#link structure 

"https://football-data.co.uk/mmz4281/" + "2526" + "/" + "E0" + ".csv"

'https://football-data.co.uk/mmz4281/2526/E0.csv'

In [9]:
# create a root variable 
root = "https://football-data.co.uk/mmz4281/"

## 2.1 Multiple Leagus

- https://football-data.co.uk/mmz4281/2526/E0.csv
- https://football-data.co.uk/mmz4281/2526/E1.csv
- https://football-data.co.uk/mmz4281/2526/E2.csv
- https://football-data.co.uk/mmz4281/2526/E3.csv
- https://football-data.co.uk/mmz4281/2526/EC.csv

In [10]:
# creating a list of leagus
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']

frames = [] # create an empty list 
 

# looping through leagues, read multiple csv's and append to a list 
for league in leagues: 
    df = pd.read_csv(root + '2526' + '/' + league + '.csv')
    frames.append(df)   #to store each dataframe in the list

In [11]:
# length of frames list
len(frames)

5

In [14]:
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,EC,25/04/2026,12:30,Scunthorpe,Eastleigh,0,1,A,0,1,...,1.85,1.95,NaN,NaN,1.85,1.95,1.80,1.88,NaN,NaN
548,EC,25/04/2026,12:30,Southend,Wealdstone,2,1,H,2,1,...,1.83,1.98,NaN,NaN,1.83,1.98,1.78,1.91,NaN,NaN
549,EC,25/04/2026,12:30,Tamworth,Braintree Town,5,1,H,2,1,...,1.78,2.03,NaN,NaN,1.83,2.03,1.77,1.93,NaN,NaN
550,EC,25/04/2026,12:30,Woking,Halifax,0,1,A,0,0,...,2.08,1.73,NaN,NaN,2.08,1.75,1.99,1.72,NaN,NaN
551,EC,25/04/2026,12:30,Yeovil,Solihull,1,4,A,1,4,...,1.78,2.03,NaN,NaN,1.78,2.03,1.73,1.97,NaN,NaN