In [3]:
import pandas as pd

In [4]:
# reading and showing the dataframe 
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# 1. Sort a DataFrame

In [ ]:
# sort by one column 
df_exams.sort_values(by= 'math score') #we can use it without the "by="

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
962,female,group E,associate's degree,standard,none,100,100,100
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100

In [6]:
# sort descending by one column 
df_exams.sort_values(by="math score", ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
451,female,group E,some college,standard,none,100,92,97
458,female,group E,bachelor's degree,standard,none,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93
623,male,group A,some college,standard,completed,100,96,86
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33
787,female,group B,some college,standard,none,19,38,32
17,female,group B,some high school,free/reduced,none,18,32,28
980,female,group B,high school,free/reduced,none,8,24,23
59,female,group C,some high school,free/reduced,none,0,17,10

In [ ]:
# sort descending by multiple columns 
df_exams.sort_values(by=["math score", "reading score"], ascending=False)
# but this didn't update the dataframe, it's just a copy

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
149,male,group E,associate's degree,free/reduced,completed,100,100,93
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
625,male,group D,some college,standard,completed,100,97,99
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33
787,female,group B,some college,standard,none,19,38,32
17,female,group B,some high school,free/reduced,none,18,32,28
980,female,group B,high school,free/reduced,none,8,24,23
59,female,group C,some high school,free/reduced,none,0,17,10

In [11]:
# sort descending by multiple columns update dataframe
df_exams.sort_values(by=["math score", "reading score"], ascending=False,
                     inplace = True) #to update the dataframe we need to use inplace = True

In [12]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
149,male,group E,associate's degree,free/reduced,completed,100,100,93
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
625,male,group D,some college,standard,completed,100,97,99
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33
787,female,group B,some college,standard,none,19,38,32
17,female,group B,some high school,free/reduced,none,18,32,28
980,female,group B,high school,free/reduced,none,8,24,23
59,female,group C,some high school,free/reduced,none,0,17,10

In [13]:
# sort descending with a key function
df_exams.sort_values('race/ethnicity', ascending=True,
                     key=lambda col:col.str.lower())    #lambda function is used to convert the column values to lowercase before sorting, ensuring a case-insensitive sort.

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
623,male,group A,some college,standard,completed,100,96,86
539,male,group A,associate's degree,standard,completed,97,92,86
546,female,group A,some high school,standard,completed,92,100,97
571,male,group A,bachelor's degree,standard,none,91,96,92
702,male,group A,bachelor's degree,standard,completed,87,84,87
...,...,...,...,...,...,...,...,...
807,female,group E,high school,free/reduced,none,41,45,40
383,female,group E,some high school,free/reduced,none,38,49,45
616,female,group E,bachelor's degree,standard,none,37,45,38
895,female,group E,some high school,free/reduced,none,32,34,38
76,male,group E,some high school,standard,none,30,26,22