In [1]:
import pandas as pd

In [3]:
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# 1. Create Index

In [2]:
import numpy as np
import random

In [9]:
# creating non repititive values for the index cuz index in a dataframe doesnt allow repititive values
new_index = np.arange(0, 1000)

In [10]:
# shuffling the new_index
random.shuffle(new_index)

In [11]:
# creating a new column with those random values
df_exams['new_index_column'] = new_index
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index_column
0,female,group B,bachelor's degree,standard,none,72,72,74,734
1,female,group C,some college,standard,completed,69,90,88,463
2,female,group B,master's degree,standard,none,90,95,93,139
3,male,group A,associate's degree,free/reduced,none,47,57,44,974
4,male,group C,some college,standard,none,76,78,75,587
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,61
996,male,group C,high school,free/reduced,none,62,55,55,717
997,female,group C,high school,free/reduced,completed,59,71,65,124
998,female,group D,some college,standard,completed,68,78,77,626
999,female,group D,some college,free/reduced,none,77,86,86,365

# 2. Set Index

    > set_index() helps us to use a column as index for the dataframe

In [13]:
# set new_index column as the index
df_exams.set_index('new_index_column', inplace  = True)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index_column,,,,,,,,
734,female,group B,bachelor's degree,standard,none,72,72,74
463,female,group C,some college,standard,completed,69,90,88
139,female,group B,master's degree,standard,none,90,95,93
974,male,group A,associate's degree,free/reduced,none,47,57,44
587,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
61,female,group E,master's degree,standard,completed,88,99,95
717,male,group C,high school,free/reduced,none,62,55,55
124,female,group C,high school,free/reduced,completed,59,71,65
626,female,group D,some college,standard,completed,68,78,77
365,female,group D,some college,free/reduced,none,77,86,86

# 3. Sort Index

    > It sorts the new_index_column that we created for the index

In [14]:
# sort the dataframe by new index
df_exams.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index_column,,,,,,,,
0,female,group C,bachelor's degree,standard,completed,96,100,100
1,female,group D,some college,standard,none,51,58,54
2,male,group B,some college,standard,none,79,67,67
3,male,group A,high school,standard,none,57,51,54
4,female,group D,some college,free/reduced,completed,58,63,73
...,...,...,...,...,...,...,...,...
995,male,group C,some high school,standard,completed,76,80,73
996,male,group B,high school,standard,none,62,55,54
997,female,group C,master's degree,free/reduced,none,52,65,61
998,male,group E,bachelor's degree,standard,completed,70,64,70
999,male,group C,bachelor's degree,free/reduced,none,37,56,47

In [18]:
df_exams.sort_index(ascending = False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index_column,,,,,,,,
999,male,group C,bachelor's degree,free/reduced,none,37,56,47
998,male,group E,bachelor's degree,standard,completed,70,64,70
997,female,group C,master's degree,free/reduced,none,52,65,61
996,male,group B,high school,standard,none,62,55,54
995,male,group C,some high school,standard,completed,76,80,73
...,...,...,...,...,...,...,...,...
4,female,group D,some college,free/reduced,completed,58,63,73
3,male,group A,high school,standard,none,57,51,54
2,male,group B,some college,standard,none,79,67,67
1,female,group D,some college,standard,none,51,58,54
0,female,group C,bachelor's degree,standard,completed,96,100,100