In [8]:
import pandas as pd

In [3]:
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1. Selecting two or more columns

In [5]:
# selecting 2 columns [[]]
df_exams[['gender', 'math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [6]:
# data type 
# [] means series
# [[]] means dataframe
type(df_exams[['gender', 'math score']])

pandas.DataFrame

In [7]:
# selecting two or more columns [[]]

df_exams[['gender', 'math score', 'reading score', 'writing score']]

     gender  math score  reading score  writing score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]

In [ ]:
# we can't select 2 or more columns with "."