In [4]:
import pandas as pd

In [3]:
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1. Adding a new column

### 1.1 assign()

When to use assign() ?

    > Add multiple columns in a single line of codes 
    > When you need to overwrite the values of an existing columns (best practice)

-> It returns a new object (a copy) with all the original columns in addition to the new ones

In [5]:
import numpy as np

In [6]:
# create random numbers for our new score columns 
score1 = np.random.randint(1, 100, size=1000)
score2 = np.random.randint(1, 100, size=1000)

In [7]:
# create a series using the random numbers 
series1 = pd.Series(score1, index=np.arange(0,1000))
series2 = pd.Series(score2, index=np.arange(0,1000))

In [8]:
series1

0       4
1      71
2      57
3      11
4      84
       ..
995    86
996     1
997    58
998    68
999    15
Length: 1000, dtype: int32

In [10]:
# using assign() to add multiple columns 
# we have to overwrite the df_exam to see the changes everywhere 
df_exams = df_exams.assign(score1=series1, score2=series2)

In [11]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,4,97
1,female,group C,some college,standard,completed,69,90,88,71,29
2,female,group B,master's degree,standard,none,90,95,93,57,58
3,male,group A,associate's degree,free/reduced,none,47,57,44,11,25
4,male,group C,some college,standard,none,76,78,75,84,80
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,86,32
996,male,group C,high school,free/reduced,none,62,55,55,1,80
997,female,group C,high school,free/reduced,completed,59,71,65,58,83
998,female,group D,some college,standard,completed,68,78,77,68,51
999,female,group D,some college,free/reduced,none,77,86,86,15,78

### 1.2 insert()

    > inserts a new column at a specific position or index

In [13]:
# using index() to add column at a specific position

df_exams.insert(1, 'test', series1)

In [14]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,4,group B,bachelor's degree,standard,none,72,72,74,4,97
1,female,71,group C,some college,standard,completed,69,90,88,71,29
2,female,57,group B,master's degree,standard,none,90,95,93,57,58
3,male,11,group A,associate's degree,free/reduced,none,47,57,44,11,25
4,male,84,group C,some college,standard,none,76,78,75,84,80
...,...,...,...,...,...,...,...,...,...,...,...
995,female,86,group E,master's degree,standard,completed,88,99,95,86,32
996,male,1,group C,high school,free/reduced,none,62,55,55,1,80
997,female,58,group C,high school,free/reduced,completed,59,71,65,58,83
998,female,68,group D,some college,standard,completed,68,78,77,68,51
999,female,15,group D,some college,free/reduced,none,77,86,86,15,78